let users = [
  {
    id: 1,
    name: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    soft_delete: false,
  },
  {
    id: 2,
    name: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    soft_delete: false,
  },
  {
    id: 3,
    name: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    soft_delete: false,
  },
  {
    id: 4,
    name: "Emily",
    lastName: "Brown",
    email: "emily.brown@example.com",
    soft_delete: false,
  },
  {
    id: 5,
    name: "Daniel",
    lastName: "Jones",
    email: "daniel.jones@example.com",
    soft_delete: false,
  },
  {
    id: 6,
    name: "Olivia",
    lastName: "Taylor",
    email: "olivia.taylor@example.com",
    soft_delete: false,
  },
  {
    id: 7,
    name: "David",
    lastName: "Miller",
    email: "david.miller@example.com",
    soft_delete: false,
  },
  {
    id: 8,
    name: "Sophia",
    lastName: "Anderson",
    email: "sophia.anderson@example.com",
    soft_delete: false,
  },
  {
    id: 9,
    name: "James",
    lastName: "Clark",
    email: "james.clark@example.com",
    soft_delete: false,
  },
  {
    id: 10,
    name: "Amelia",
    lastName: "Lee",
    email: "amelia.lee@example.com",
    soft_delete: false,
  },
  {
    id: 11,
    name: "Benjamin",
    lastName: "Hall",
    email: "benjamin.hall@example.com",
    soft_delete: false,
  },
  {
    id: 12,
    name: "Mia",
    lastName: "Lewis",
    email: "mia.lewis@example.com",
    soft_delete: false,
  },
  {
    id: 13,
    name: "William",
    lastName: "Young",
    email: "william.young@example.com",
    soft_delete: false,
  },
  {
    id: 14,
    name: "Emma",
    lastName: "Walker",
    email: "emma.walker@example.com",
    soft_delete: false,
  },
  {
    id: 15,
    name: "Alexander",
    lastName: "Martin",
    email: "alexander.martin@example.com",
    soft_delete: false,
  },
  {
    id: 16,
    name: "Abigail",
    lastName: "Hall",
    email: "abigail.hall@example.com",
    soft_delete: false,
  },
  {
    id: 17,
    name: "Henry",
    lastName: "Allen",
    email: "henry.allen@example.com",
    soft_delete: false,
  },
  {
    id: 18,
    name: "Sofia",
    lastName: "King",
    email: "sofia.king@example.com",
    soft_delete: false,
  },
  {
    id: 19,
    name: "Christopher",
    lastName: "Turner",
    email: "christopher.turner@example.com",
    soft_delete: false,
  },
  {
    id: 20,
    name: "Grace",
    lastName: "Baker",
    email: "grace.baker@example.com",
    soft_delete: false,
  },
  {
    id: 21,
    name: "John",
    lastName: "Doe",
    email: "johndoe@example.com",
    soft_delete: false,
  },
  {
    id: 22,
    name: "Jane",
    lastName: "Smith",
    email: "janesmith@example.com",
    soft_delete: false,
  },
  {
    id: 23,
    name: "Michael",
    lastName: "Johnson",
    email: "michaeljohnson@example.com",
    soft_delete: false,
  },
  {
    id: 24,
    name: "Emily",
    lastName: "Brown",
    email: "emilybrown@example.com",
    soft_delete: false,
  },
  {
    id: 25,
    name: "David",
    lastName: "Taylor",
    email: "davidtaylor@example.com",
    soft_delete: false,
  },
  {
    id: 26,
    name: "Sophia",
    lastName: "Miller",
    email: "sophiamiller@example.com",
    soft_delete: false,
  },
  {
    id: 27,
    name: "Daniel",
    lastName: "Anderson",
    email: "danielanderson@example.com",
    soft_delete: false,
  },
  {
    id: 28,
    name: "Olivia",
    lastName: "Martinez",
    email: "oliviamartinez@example.com",
    soft_delete: false,
  },
  {
    id: 29,
    name: "William",
    lastName: "Hernandez",
    email: "williamhernandez@example.com",
    soft_delete: false,
  },
  {
    id: 30,
    name: "Emma",
    lastName: "Garcia",
    email: "emmagarcia@example.com",
    soft_delete: false,
  },
  {
    id: 31,
    name: "James",
    lastName: "Lopez",
    email: "jameslopez@example.com",
    soft_delete: false,
  },
  {
    id: 32,
    name: "Ava",
    lastName: "Lewis",
    email: "avalewis@example.com",
    soft_delete: false,
  },
  {
    id: 33,
    name: "Benjamin",
    lastName: "Walker",
    email: "benjaminwalker@example.com",
    soft_delete: false,
  },
  {
    id: 34,
    name: "Mia",
    lastName: "Moore",
    email: "miamoore@example.com",
    soft_delete: false,
  },
  {
    id: 35,
    name: "Lucas",
    lastName: "Sanchez",
    email: "lucassanchez@example.com",
    soft_delete: false,
  },
  {
    id: 36,
    name: "Harper",
    lastName: "Lee",
    email: "harperlee@example.com",
    soft_delete: false,
  },
  {
    id: 37,
    name: "Henry",
    lastName: "Turner",
    email: "henryturner@example.com",
    soft_delete: false,
  },
  {
    id: 38,
    name: "Grace",
    lastName: "Parker",
    email: "graceparker@example.com",
    soft_delete: false,
  },
  {
    id: 39,
    name: "Alexander",
    lastName: "Carter",
    email: "alexandercarter@example.com",
    soft_delete: false,
  },
  {
    id: 40,
    name: "Henry",
    lastName: "Pacheco",
    email: "henrydjpacheco@gmail.com",
    soft_delete: false,
  },
];

module.exports = users;
