let servicios =[
    { servicio: 'Wifi', icono: '📶' },
    { servicio: 'TV', icono: '📺' },
    { servicio: 'Aire acondicionado', icono: '❄️' },
    { servicio: 'Calefacción', icono: '🔥' },
    { servicio: 'Cocina', icono: '🍳🔪' },
    { servicio: 'Desayuno', icono: '🍳' },
    { servicio: 'Jacuzzi', icono: '🛁' },
    { servicio: 'Piscina', icono: '🏊' },
    { servicio: 'Estacionamiento', icono: '🅿️' },
    { servicio: 'Gimnasio', icono: '💪' },
    { servicio: 'Mascotas permitidas', icono: '🐶' },
    { servicio: 'Vistas al mar', icono: '🌊' },
    { servicio: 'Chimenea', icono: '🔥' },
    { servicio: 'Jardín', icono: '🌳' },
    { servicio: 'Terraza', icono: '🌅' },
    { servicio: 'Baño privado', icono: '🚽' },
    { servicio: 'Transporte desde/hacia el aeropuerto', icono: '🚖' },
    { servicio: 'Lavandería', icono: '🧺' },
    { servicio: 'Permite fumar', icono: '🚬' },
    { servicio: 'Accesibilidad', icono: '♿️' },
    { servicio: 'Desayuno incluido', icono: '🍳' },
    { servicio: 'Servicio de habitaciones', icono: '🛎️' },
    { servicio: 'Servicio de limpieza', icono: '🧹' },
    { servicio: 'Spa', icono: '💆' },
    { servicio: 'Sauna', icono: '🧖' }
  ]
  module.exports = {servicios}