let type = [
  { type: "Apartamento", icono: "🏢" },
  { type: "Casa", icono: "🏠" },
  { type: "Villa", icono: "🏰" },
  { type: "Casa adosada", icono: "🏘️" },
  { type: "Loft", icono: "🏭" },
  { type: "Habitación privada", icono: "🛌" },
  { type: "Habitación compartida", icono: "🛌" },
  { type: "Cabaña", icono: "🏡" },
  { type: "Castillo", icono: "🏰" },
  { type: "Barco", icono: "🛳️" },
  { type: "Iglú", icono: "🏠" },
  { type: "Caravana", icono: "🚐" },
  { type: "Casa de huéspedes", icono: "🏠" },
  { type: "Bungalow", icono: "🏡" },
  { type: "Ático", icono: "🏢" },
  { type: "Chalé", icono: "🏠" },
  { type: "Rancho", icono: "🏡" },
  { type: "Departamento", icono: "🏢" },
  { type: "Suite de hotel", icono: "🏨" },
  { type: "Casa cueva", icono: "🏠" },
  { type: "Granja", icono: "🏡" },
  { type: "Lodge", icono: "🏨" },
  { type: "Molino", icono: "🏭" },
  { type: "Chalet alpino", icono: "🏔️" },
  { type: "Casa de campo", icono: "🏡" },
  { type: "Torre", icono: "🗼" },
  { type: "Casa de vacaciones", icono: "🏡" },
  { type: "Casa de playa", icono: "🏖️" },
  { type: "Casa flotante", icono: "🚣" },
  { type: "Departamento en complejo residencial", icono: "🏢" },
  { type: "Apartotel", icono: "🏢" },
];

module.exports = { type };
